config/routes.rb
Rails.application.routes.draw do
  resources :postings

  post '/login' => 'authentication#login'
  get '/authenticate' => 'authentication#authenticate'
  get '/api_index' => 'postings#api_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/json_web_token.rb
require 'jwt'
class JsonWebToken

  def self.encode(payload)
    JWT.encode payload, nil, 'none'
  end

  def self.decode(token)
    JWT.decode token, nil, false
  end
end

app/models/posting.rb
class Posting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  def authenticate
    # token=params[:token]
    # puts auth_token
    payload=JsonWebToken.decode(auth_token)
    @currnet_user= User.find(payload.first["sub"])
    # puts @currnet_user.id
    # puts @currnet_user.email
    # puts payload[:sub]
  rescue JWT::DecodeError
    render json: {errors: ["Invalid Token Error"]}, status: :unauthorized
  end
  def auth_token
    @auth_token ||= request.headers.fetch("Authorization", "")
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def login
    u=User.find_by(email: params[:user][:email])
    if u and u.authenticate(params[:user][:password])
      render json: {token: JsonWebToken.encode({sub: u.id})}
    else
      render json: {errors: ["Invalid email or password"]}
    end
  end

  def authenticate
    # token=params[:token]
    # puts auth_token
    payload=JsonWebToken.decode(auth_token)
    puts payload.first["sub"]
    @currnet_user= User.find(payload.first["sub"])
    # puts @currnet_user.id
    # puts @currnet_user.email
    # puts payload[:sub]
  rescue JWT::DecodeError
    rendor json: {errors: ["Invalid Token Error"]}, status: :unauthorized
  end

  def auth_token
    @auth_token ||= request.headers.fetch("Authorization", "")
  end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_action :set_posting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:index]
  # GET /postings
  # GET /postings.json
  def index
    @postings = Posting.all
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
  end

  # GET /postings/new
  def new
    @posting = Posting.new
  end

  # GET /postings/1/edit
  def edit
  end

  def api_index
    @postings=Posting.all
    render json: @postings
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = Posting.new(posting_params)

    respond_to do |format|
      if @posting.save
        format.html { redirect_to @posting, notice: 'Posting was successfully created.' }
        format.json { render :show, status: :created, location: @posting }
      else
        format.html { render :new }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postings/1
  # PATCH/PUT /postings/1.json
  def update
    respond_to do |format|
      if @posting.update(posting_params)
        format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @posting }
      else
        format.html { render :edit }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting.destroy
    respond_to do |format|
      format.html { redirect_to postings_url, notice: 'Posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posting
      @posting = Posting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posting_params
      params.require(:posting).permit(:title, :content, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Post</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/postings/_form.html.erb
<%= form_with(model: posting, local: true) do |form| %>
  <% if posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

      <ul>
      <% posting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :posting_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :posting_content %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :posting_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/postings/edit.html.erb
<h1>Editing Posting</h1>

<%= render 'form', posting: @posting %>

<%= link_to 'Show', @posting %> |
<%= link_to 'Back', postings_path %>

app/views/postings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Postings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postings.each do |posting| %>
      <tr>
        <td><%= posting.title %></td>
        <td><%= posting.content %></td>
        <td><%= posting.image_url %></td>
        <td><%= link_to 'Show', posting %></td>
        <td><%= link_to 'Edit', edit_posting_path(posting) %></td>
        <td><%= link_to 'Destroy', posting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Posting', new_posting_path %>

app/views/postings/new.html.erb
<h1>New Posting</h1>

<%= render 'form', posting: @posting %>

<%= link_to 'Back', postings_path %>

app/views/postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @posting.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @posting.content %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @posting.image_url %>
</p>

<%= link_to 'Edit', edit_posting_path(@posting) %> |
<%= link_to 'Back', postings_path %>